:tv: updating pypi classifiers'

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -11,6 +11,12 @@ jobs:
       - uses: actions/checkout@v4
         with:
           submodules: recursive  # Ensure submodules are checked out
+      - name: Check cookiecutter present
+        run: |
+          if [ ! -f torchapp/cookiecutter/cookiecutter.json ]; then
+            echo "Missing file: torchapp/cookiecutter/cookiecutter.json"
+            exit 1
+          fi
       - name: Install poetry
         run: pipx install poetry
       - name: Install dependencies
